### ISSUE TITLE
Support for CSS classes

### ISSUE THREAD

**Issue by shirakaba** [nodegui/svelte-nodegui#6]
See:

* https://doc.qt.io/qt-5/stylesheet-reference.html
* https://doc.qt.io/qt-5/stylesheet-syntax.html
* https://forum.qt.io/topic/17237/using-css-class/6

The forum post suggested this approach:

```js
parent.nativeView.setProperty("class", "my_supa_button");
```

```css
*[class=my_supa_button] {
    font: 50px;
    color: black;
}
```
