### ISSUE TITLE
Support for styling elements

### ISSUE THREAD

**Issue by shirakaba** [nodegui/svelte-nodegui#7]
This is possible, as long as you don't write it into a <style> element (Svelte compiles it out, as it finds no <QtLabel> element in your HTML tree):

```css
QLabel {
    color: red;
}
```

This would be preferred, as we use elements with names like <text>:

```css
text {
    color: red;
}
```

To achieve this, we'd need to implement a Svelte postprocessor that renames `text` to the corresponding underlying component, i.e. `QLabel`.

We could work around this using [global styles](https://github.com/sveltejs/svelte/issues/1594#issuecomment-405269805), with the natural caveat that they would be unscoped. For now, the best we can do is:

```css
:global(QLabel) {
    color: red;
}
```
